name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: hellojqk/http-proxy-analysis

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Use Node.js 12.x
      uses: actions/setup-node@v2.1.2
      with:
        node-version: 12.x
            
#     - name: Build UI
#       run: |
#           cd ./ui
#           npm i
#           npm run build
          
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15.4

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v -o ./bin/app .
    
    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@6efc2b01cbb63cfc68c370c6c806586fa6384a3a
      uses: docker/build-push-action@v2.1.0
      with:
        # List of tags
        tags: hellojqk/http-proxy-analysis

#     - name: Build image
#       run: |
#           ls -l ./bin/
#           ls -l ./ui/dist/
#           docker build . --file Dockerfile --tag $IMAGE_NAME

    - name: Log into registry
      run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
    
    - name: Push image
      run: |
          docker tag $IMAGE_NAME $IMAGE_NAME:dev
          docker push $IMAGE_NAME:dev

#     - name: Test
#       run: go test -v .
